[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "imbalanced-calibrate"
dynamic = ["version"]
authors = [
  { name="Jules Lanari-Collard", email="jules_collard@yahoo.co.uk" },
]
description = "An open-source library providing wrapper estimators to analytically correct for bias induced by imbalanced learning methods."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy>=2.0.2",
  "scikit-learn>=1.6.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/jules-collard/imbalanced-calibrate"
Issues = "https://github.com/jules-collard/imbalanced-calibrate/issues"

[project.optional-dependencies]
resampling = [
    "imbalanced-learn>=0.14.2",
]

[tool.setuptools_scm]
version_file = "imbcalibrate/_version.py"

[dependency-groups]
test = [
  "imbalanced-learn>=0.14.2",
  "lightgbm>=4.7.0",
  "pytest",
  "pytest-cov",
  "xgboost>=3.2.0",
]
lint = [
  # The version below should be aligned with the one of `.pre-commit-config.yaml`
  "black==23.3.0",
  "pre-commit==3.7.1",
  "ruff>=0.5.3",
]
doc = [
  "matplotlib",
  "numpydoc",
  "pydata-sphinx-theme",
  "setuptools-scm>=8",
  "sphinx",
  "sphinx-design",
  "sphinx-gallery",
  "sphinx-prompt",
]
dev = [
  {include-group = "test"},
  {include-group = "lint"},
  {include-group = "doc"},
]

[tool.black]
line-length = 88
target_version = ['py38', 'py39', 'py310']
preview = true
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.vscode
)/
'''
force-exclude = "imbcalibrate/_version.py"

[tool.ruff]
# max line length for black
line-length = 88
target-version = "py38"
exclude=[
    ".git",
    "__pycache__",
    "dist",
    "doc/_build",
    "doc/auto_examples",
    "build",
    "imbcalibrate/_version.py",
]

[tool.ruff.lint]
# all rules can be found here: https://beta.ruff.rs/docs/rules/
select = ["E", "F", "W", "I"]
ignore=[
    # space before : (needed for how black formats slicing)
    "E203",
    # do not assign a lambda expression, use a def
    "E731",
    # do not use variables named 'l', 'O', or 'I'
    "E741",
]

[tool.ruff.lint.per-file-ignores]
# It's fine not to put the import at the top of the file in the examples
# folder.
"examples/*"=["E402"]
"doc/conf.py"=["E402"]
"doc/_templates/numpydoc_docstring.py"=["F821", "W292"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --color=yes"
doctest_optionflags = "NORMALIZE_WHITESPACE"
