name: Documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        version: "latest"

    - name: Install documentation dependencies
      run: uv sync --group doc

    - name: Build documentation
      run: |
        cd doc
        uv run make html

    - name: Update the main gh-page website
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/_build/html
        commit_message: "[ci skip] ${{ github.event.head_commit.message }}"
