name: Unit Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        environment: [test]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: uv sync --group ${{ matrix.environment }}

      - name: Run tests
        run: uv run pytest -vsl --cov=imbcalibrate --cov-report=xml imbcalibrate

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jules-collard/imbalanced-calibrate
